name: Build & Test

on:
  push:
    branches:
      - main
      - next
      - "v*"
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *" # daily, at 3am

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup go-task
        uses: arduino/setup-task@v2

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8

      - name: Setup cache
        uses: actions/cache@v4.0.2
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run lint
        run: |
          task lint

      - name: Run tests
        run: |
          task test
